# https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html
[tool.black]
line-length = 200

# https://beta.ruff.rs/docs/settings/
[tool.ruff]
line-length = 200
# https://beta.ruff.rs/docs/rules/
select = ["E", "W", "F"]
ignore = ["F401", "F601"]
# Exclude a variety of commonly ignored directories.
respect-gitignore = true
ignore-init-module-imports = true
